# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jcropper}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Ziegler"]
  s.date = %q{2011-05-09}
  s.description = %q{}
  s.email = %q{ryan@symbolforce.com}
  s.extra_rdoc_files = [
    "README.rdoc",
     "TODO"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "TODO",
     "VERSION",
     "generators/jcropper/USAGE",
     "generators/jcropper/jcropper_generator.rb",
     "generators/jcropper/templates/jcropper_migration.rb.erb",
     "install.rb",
     "jcropper.gemspec",
     "lib/generators/jcropper/jcropper_generator.rb",
     "lib/jcropper.rb",
     "lib/jcropper/cropped_image.rb",
     "lib/jcropper/helpers.rb",
     "lib/jcropper/jcropper.rb",
     "lib/jcropper/tasks.rb",
     "lib/paperclip_processors/jcropper.rb",
     "lib/railtie.rb",
     "lib/tasks/jcropper.rake",
     "public/images/Jcrop.gif",
     "public/javascripts/jcropper.js",
     "public/javascripts/jquery.Jcrop.min.js",
     "public/stylesheets/jquery.Jcrop.css",
     "rails/init.rb",
     "test/jcropper_test.rb",
     "test/test_helper.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/syfo/jcropper}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{gem plugin wrapping jquery.jcrop.js}
  s.test_files = [
    "test/jcropper_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

